### ISSUE TITLE
flowbite only runs on firefox

### ISSUE THREAD

**Issue by VRyo** [themesberg/flowbite-vue#120]
hello, my flowbite only runs on firefox, I use it for carousel and dropdown, but those two functions only run on firefox, can anyone help?

here my tailwind.config.js

```
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
    "./node_modules/flowbite-vue/**/*.{js,jsx,ts,tsx}"
  ],
  theme: {
    extend: {},
  },
  important: true,
  plugins: [
    require('flowbite/plugin')
  ],
}
```

here my main.js

```
import { createApp } from 'vue'
import router from './router'
import App from './App.vue'

import 'datatables.net-bs';
import 'datatables.net-responsive-bs';
import 'datatables.net-bs/css/dataTables.bootstrap.min.css';
import 'datatables.net-responsive-bs/css/responsive.bootstrap.min.css';
import "vue-select/dist/vue-select.css";
import VueSweetalert2 from 'vue-sweetalert2';
import 'sweetalert2/dist/sweetalert2.min.css';
import store from './store';
import vSelect from "vue-select";
import './tailwind.css'
import 'flowbite';


import { Form } from 'vform'
window.Form = Form; 

import $ from 'jquery';

const app = createApp(App)
app.use(router)
app.use(store)
app.use(VueSweetalert2)
app.use("v-select", vSelect)
app.mount('#app')
```

**Comment by cogor** [comment]
Hey, carousel component added in version 0.0.10, I released it just now.
Please check it

**Comment by VRyo** [comment]
my problem is still there, flowbite only works on firefox, i try in chrome and not work, I tried other components too like that

**Comment by cogor** [comment]
> my problem is still there, flowbite only works on firefox, i try in chrome and not work, I tried other components too like that

Can you create repo with example?
I created [sandbox](https://stackblitz.com/edit/vitejs-vite-afszcj?file=src/App.vue) and it's works

**Comment by VRyo** [comment]
it worked, it turns out that I haven't updated, my bad
